package Profile;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 *
 * @author Gaole Elia
 * @version 1.0
 */
public class ProfileServlet extends HttpServlet {

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        response.setContentType("text/html");
        PrintWriter out = response.getWriter();

        HttpSession session = request.getSession(true);
        String name = (String) session.getAttribute("usrnm");
        if (session != null) {
            
            
            out.println("    <head>\n"
                    + "        <meta charset=\"utf-8\">\n"
                    + "        <!--  This file has been downloaded from https://bootdey.com  -->\n"
                    + "        <!--  All snippets are MIT license https://bootdey.com/license -->\n"
                    + "        <title>Profile</title>\n"
                    + "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                    + "        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\n"
                    + "        <link href=\"http://netdna.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\">\n"
                    + "        <style type=\"text/css\">\n"
                    + "            body{\n"
                    + "                margin-top:20px;\n"
                    + "                background:#f8f8f8\n"
                    + "            }\n"
                    + "\n"
                    + "            a{\n"
                    + "                color:#fff;\n"
                    + "            }\n"
                    + "        </style>\n"
                    + "    </head>\n"
                    + "    <body>\n"
                    + "        <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n"
                    + "        <div class=\"container\">\n"
                    + "\n"
                    + "\n"
                    + "            <div class=\"col\">\n"
                    + "                <div class=\"row\">\n"
                    + "                    <div class=\"col mb-3\">\n"
                    + "                        <div class=\"card\">\n"
                    + "                            <div class=\"card-body\">\n"
                    + "                                <div class=\"e-profile\">\n"
                    + "                                    <div class=\"row\">\n"
                    + "                                        <div class=\"col-12 col-sm-auto mb-3\">\n"
                    + "                                            <div class=\"mx-auto\" style=\"width: 140px;\">\n"
                    + "                                                <div class=\"d-flex justify-content-center align-items-center rounded\" style=\"height: 140px; background-color: rgb(233, 236, 239);\">\n"
                    + "                                                    <span style=\"color: rgb(166, 168, 170); font: bold 8pt Arial;\">140x140</span>\n"
                    + "                                                </div>\n"
                    + "                                            </div>\n"
                    + "                                        </div>\n"
                    + "                                        <div class=\"col d-flex flex-column flex-sm-row justify-content-between mb-3\">\n"
                    + "                                            <div class=\"text-center text-sm-left mb-2 mb-sm-0\">\n"
                    + "                                                <h4 class=\"pt-sm-2 pb-1 mb-0 text-nowrap\">" + name + "</h4>\n"
                    + "                                                <p class=\"mb-0\">" + name + "</p>\n"
                    + "                                                <div class=\"text-muted\"><small>Last seen 2 hours ago</small></div>\n"
                    + "                                                <div class=\"mt-2\">\n"
                    + "                                                    <button class=\"btn btn-primary\" type=\"button\">\n"
                    + "                                                        <i class=\"fa fa-fw fa-camera\"></i>\n"
                    + "                                                        <span>Change Photo</span>\n"
                    + "                                                    </button>\n"
                    + "                                                </div>\n"
                    + "                                            </div>\n"
                    + "                                            <div class=\"text-center text-sm-right\">\n"
                    + "                                                <span style=\"background-color: dodgerblue;\"class=\"badge badge-secondary\">admin</span>\n"
                    + "                                                <div class=\"text-muted\"><small>Joined 09 Dec 2017</small></div>\n"
                    + "                                            </div>\n"
                    + "                                        </div>\n"
                    + "                                    </div>\n"
                    + "                                    <ul class=\"nav nav-tabs\">\n"
                    + "                                        <li class=\"nav-item\"><a href=\"\" class=\"active nav-link\">Settings</a></li>\n"
                    + "                                    </ul>\n"
                    + "                                    <div class=\"tab-content pt-3\">\n"
                    + "                                        <div class=\"tab-pane active\">\n"
                    + "                                            <form class=\"form\" novalidate=\"\">\n"
                    + "                                                <div class=\"row\">\n"
                    + "                                                    <div class=\"col\">\n"
                    + "                                                        <div class=\"row\">\n"
                    + "                                                            <div class=\"col\">\n"
                    + "                                                                <div class=\"form-group\">\n"
                    + "                                                                    <label>Full Name</label>\n"
                    + "                                                                    <input class=\"form-control\" type=\"text\" name=\"name\" placeholder=\"Full Name\" value=\"" + name + "\">\n"
                    + "                                                                </div>\n"
                    + "                                                            </div>\n"
                    + "                                                            <div class=\"col\">\n"
                    + "                                                                <div class=\"form-group\">\n"
                    + "                                                                    <label>Username</label>\n"
                    + "                                                                    <input class=\"form-control\" type=\"text\" name=\"username\" placeholder=\"Username\" value=\"" + name + "\">\n"
                    + "                                                                </div>\n"
                    + "                                                            </div>\n"
                    + "                                                        </div>\n"
                    + "                                                        <div class=\"row\">\n"
                    + "                                                            <div class=\"col\">\n"
                    + "                                                                <div class=\"form-group\">\n"
                    + "                                                                    <label>Email</label>\n"
                    + "                                                                    <input class=\"form-control\" type=\"text\" placeholder=\"user@example.com\" value=\"\">\n"
                    + "                                                                </div>\n"
                    + "                                                            </div>\n"
                    + "                                                        </div>\n"
                    + "                                                        <div class=\"row\">\n"
                    + "                                                            <div class=\"col mb-3\">\n"
                    + "                                                                <div class=\"form-group\">\n"
                    + "                                                                    <label>About</label>\n"
                    + "                                                                    <textarea class=\"form-control\" rows=\"5\" placeholder=\"My Bio\"></textarea>\n"
                    + "                                                                </div>\n"
                    + "                                                            </div>\n"
                    + "                                                        </div>\n"
                    + "                                                    </div>\n"
                    + "                                                </div>\n"
                    + "                                                <div class=\"row\">\n"
                    + "                                                    <div class=\"col-12 col-sm-6 mb-3\">\n"
                    + "                                                        <div class=\"mb-2\"><b>Change Password</b></div>\n"
                    + "                                                        <div class=\"row\">\n"
                    + "                                                            <div class=\"col\">\n"
                    + "                                                                <div class=\"form-group\">\n"
                    + "                                                                    <label>Current Password</label>\n"
                    + "                                                                    <input class=\"form-control\" type=\"password\" placeholder=\"••••••\">\n"
                    + "                                                                </div>\n"
                    + "                                                            </div>\n"
                    + "                                                        </div>\n"
                    + "                                                        <div class=\"row\">\n"
                    + "                                                            <div class=\"col\">\n"
                    + "                                                                <div class=\"form-group\">\n"
                    + "                                                                    <label>New Password</label>\n"
                    + "                                                                    <input class=\"form-control\" type=\"password\" placeholder=\"••••••\">\n"
                    + "                                                                </div>\n"
                    + "                                                            </div>\n"
                    + "                                                        </div>\n"
                    + "                                                        <div class=\"row\">\n"
                    + "                                                            <div class=\"col\">\n"
                    + "                                                                <div class=\"form-group\">\n"
                    + "                                                                    <label>Confirm <span class=\"d-none d-xl-inline\">Password</span></label>\n"
                    + "                                                                    <input class=\"form-control\" type=\"password\" placeholder=\"••••••\"></div>\n"
                    + "                                                            </div>\n"
                    + "                                                        </div>\n"
                    + "                                                    </div>\n"
                    + "                                                    <div class=\"col-12 col-sm-5 offset-sm-1 mb-3\">\n"
                    + "                                                        <div class=\"mb-2\"><b>Keeping in Touch</b></div>\n"
                    + "                                                        <div class=\"row\">\n"
                    + "                                                            <div class=\"col\">\n"
                    + "                                                                <label>Email Notifications</label>\n"
                    + "                                                                <div class=\"custom-controls-stacked px-2\">\n"
                    + "                                                                    <div class=\"custom-control custom-checkbox\">\n"
                    + "                                                                        <input type=\"checkbox\" class=\"custom-control-input\" id=\"notifications-blog\" checked=\"\">\n"
                    + "                                                                        <label class=\"custom-control-label\" for=\"notifications-blog\">Blog posts</label>\n"
                    + "                                                                    </div>\n"
                    + "                                                                    <div class=\"custom-control custom-checkbox\">\n"
                    + "                                                                        <input type=\"checkbox\" class=\"custom-control-input\" id=\"notifications-news\" checked=\"\">\n"
                    + "                                                                        <label class=\"custom-control-label\" for=\"notifications-news\">Newsletter</label>\n"
                    + "                                                                    </div>\n"
                    + "                                                                    <div class=\"custom-control custom-checkbox\">\n"
                    + "                                                                        <input type=\"checkbox\" class=\"custom-control-input\" id=\"notifications-offers\" checked=\"\">\n"
                    + "                                                                        <label class=\"custom-control-label\" for=\"notifications-offers\">Personal Offers</label>\n"
                    + "                                                                    </div>\n"
                    + "                                                                </div>\n"
                    + "                                                            </div>\n"
                    + "                                                        </div>\n"
                    + "                                                    </div>\n"
                    + "                                                </div>\n"
                    + "                                                <div class=\"row\">\n"
                    + "                                                    <div class=\"col d-flex justify-content-end\">\n"
                    + "                                                        <button class=\"btn btn-primary\" type=\"submit\">Save Changes</button>\n"
                    + "                                                    </div>\n"
                    + "                                                </div>\n"
                    + "                                            </form>\n"
                    + "\n"
                    + "                                        </div>\n"
                    + "                                    </div>\n"
                    + "                                </div>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "\n"
                    + "                    <div class=\"col-12 col-md-3 mb-3\">\n"
                    + "                        <div class=\"card mb-3\">\n"
                    + "                            <div class=\"card-body\">\n"
                    + "                                <div class=\"px-xl-3\">\n"
                    + "                                    <button onclick=\"window.location.href = 'home.html'\" style=\"background-color: dodgerblue; border-color: transparent;\" class=\"btn btn-block btn-secondary\">\n"
                    + "                                            <i class=\"fa fa-sign-out\"></i>\n"
                    + "                                            <span >Go Back</span>\n"
                    + "                                    </button>\n"
                    + "                                </div>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"card mb-3\">\n"
                    + "                            <div class=\"card-body\">\n"
                    + "                                <div class=\"px-xl-3\">\n"
                    + "                                    <button onclick=\"window.location.href = 'LogoutServlet'\"class=\"btn btn-block btn-secondary\">\n"
                    + "                                        <i class=\"fa fa-sign-out\"></i>\n"
                    + "                                        <span>Logout</span>\n"
                    + "                                    </button>\n"
                    + "                                </div>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"card\">\n"
                    + "                            <div class=\"card-body\">\n"
                    + "                                <h6 class=\"card-title font-weight-bold\">Support</h6>\n"
                    + "                                <p class=\"card-text\">Get fast, free help from our friendly assistants.</p>\n"
                    + "                                <button type=\"button\"  class=\"btn btn-primary\">Contact Us</button>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div>\n"
                    + "\n"
                    + "            </div>\n"
                    + "        </div>\n"
                    + "\n"
                    + "\n"
                    + "    <script src=\"http://netdna.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\n"
                    + "    <script type=\"text/javascript\">\n"
                    + "\n"
                    + "    </script>");

        } else {
            out.print("Please login first");
            request.getRequestDispatcher("login.html");
        }

        out.close();
    }
}
